- hosts: all

  tasks:
   - name: install ntp
     become: yes
     action: "{{ ansible_pkg_mgr }} name=ntp state=present"
   
   - name: enable ntp service
     become: yes
     service: name={% if ansible_os_family == 'RedHat' %}ntpd{% else %}ntp{% endif %}
              state=started enabled=yes
   
   - name: install yum-cron
     become: yes
     yum: name=yum-cron state=present
     when: ansible_os_family == 'RedHat'
   
   - name: install cron-apt
     become: yes
     apt: name=cron-apt state=present
     when: ansible_os_family == 'Debian'

