- hosts: reports
  roles:
      - role: testsuite-installdeps

- hosts: reports
  roles:
      - role: reports
        reports_user: tbtsreports
        reports_config: receive-reports
        reports_keys:
            - "{{ lookup('file', 'ssh_pubkeys/fedora20-tbbtests.mars-attacks.org') }}"
            - "{{ lookup('file', 'ssh_pubkeys/windows-tbbtests') }}"
            - "{{ lookup('file', 'ssh_pubkeys/osx-tests') }}"
