- hosts: testsuite
  roles:
      - testsuite-installdeps

- hosts: testsuite
  roles:
      - role: testsuite
        testsuite_user: tbts
#        testsuite_minute: "*/15"
        testsuite_options:
            - "--config=linus-nightly {{ testsuite_upload_to }}"
            - "--config=release {{ testsuite_upload_to }}"
            - "{% if virustotal %}--config=release-virustotal {{ testsuite_upload_to }}{% endif %}"
            - "{% if virustotal %}--config=linus-nightly-virustotal {{ testsuite_upload_to }}{% endif %}"

- hosts: reports
  roles:
      - role: reports
        reports_user: tbtsreports
        reports_config: receive-reports
        reports_keys:
            - "{{ lookup('file', 'ssh_pubkeys/fedora20-tbb-test') }}"
            - "{{ lookup('file', 'ssh_pubkeys/fedora20-firefoxbuilder') }}"
            - "{{ lookup('file', 'ssh_pubkeys/fedora20-tbbtests.mars-attacks.org') }}"

