---
- hosts: virustotal
  vars:
      - testsuite_user: virustotal
  roles:
      - role: testsuite-installdeps
      - role: testsuite
        testsuite_minute: "*/15"
        testsuite_options:
            - "--config=release-virustotal {{ testsuite_upload_to }}"
            - "--config=linus-nightly-virustotal {{ testsuite_upload_to }}"
  tasks:
      - name: copy virustotal api key
        become: yes
        become_user: '{{ testsuite_user }}'
        copy: content={{ virustotal_apikey }} dest=/home/{{ testsuite_user }}/.virustotal.api-key
              owner={{ testsuite_user }} mode=0600
        when: virustotal_apikey is defined
