---

- name: create testsuite data user
  user: name={{ data_user }} comment="Tor Browser Test Suite Data"
        createhome=yes home=/home/{{ data_user }}
  become: yes

- name: change permissions on home directory
  become: yes
  file: path=/home/{{ data_user }} state=directory mode=0711

- name: clone test suite in testsuite home
  become: yes
  become_user: "{{ data_user }}"
  git: repo={{ testsuite_git_url }} dest=/home/{{ data_user }}/testsuite
       version={{ testsuite_git_commit }}

- name: create self signed SSL cert
  become: yes
  command: openssl req -new -nodes -x509 -subj "/CN={{ data_hostname }}" -days 10000 -keyout /etc/pki/tls/private/{{ data_hostname }}.key -out /etc/ssl/certs/{{ data_hostname }}.cert -extensions v3_ca
  args:
      creates: /etc/ssl/certs/{{ data_hostname }}.cert

- name: add httpd configuration
  become: yes
  template: src=httpd_test-data.conf
            dest=/etc/httpd/conf.d/{{ data_user }}.conf
  notify:
      - restart httpd
