---

- name: install yum-utils
  become: yes
  yum: name=yum-utils state=present

- name: copy firefox.spec
  copy: dest={{ ansible_env.HOME }}/firefox.spec src=firefox.spec

- name: install firefox build dependencies
  become: yes
  command: yum-builddep -y {{ ansible_env.HOME }}/firefox.spec

- name: install other firefox build dependencies
  become: yes
  yum: name={{ item }} state=present
  with_items:
      - yasm
      - gstreamer-devel
      - gstreamer-plugins-base-devel
