---
- name: install web server
  sudo: yes
  apt: name=apache2 state=present

- name: install mod_ssl
  sudo: yes
  apt: name=libapache2-mod-nss state=present

- name: start web server
  sudo: yes
  service: name={{ httpd_service }} enabled=yes state=started

