---
- name: install web server
  become: yes
  apt: name=apache2 state=present

- name: install mod_ssl
  become: yes
  apt: name=libapache2-mod-nss state=present

- name: start web server
  become: yes
  service: name={{ httpd_service }} enabled=yes state=started

